# will never run on a git push or merge request event.
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always
    
variables:
  FULL_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
    
stages:
  - build
  - deploy
    
build:
  stage: build
  tags:
    - shell
  before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  - echo "$DH_PW" | docker login -u $DH_USER --password-stdin
  script:
    - "docker build -t $FULL_IMAGE ubuntu"
deploy:
  stage: deploy
  tags:
  - shell  
  after_script:
    - docker logout $CI_REGISTRY
    - docker logout
  script:
    - "docker tag $FULL_IMAGE $CI_REGISTRY_IMAGE:ubuntu"
    - "docker tag $FULL_IMAGE $CI_REGISTRY_IMAGE:latest"
    - "docker tag $FULL_IMAGE cmptstks/baseimage:ubuntu"
    - "docker tag $FULL_IMAGE cmptstks/baseimage:latest"
    - "docker push $FULL_IMAGE"
    - "docker push $CI_REGISTRY_IMAGE:ubuntu"
    - "docker push $CI_REGISTRY_IMAGE:latest"
    - "docker push cmptstks/baseimage:ubuntu"
    - "docker push cmptstks/baseimage:latest"
